name: Dev Pull Request Validator
permissions:
  id-token: write
  contents: read
on:
  push:
    branches:
      - 'main'
    paths:
      - src/**
      - Dockerfile
      - '**.gradle'
      - gradle.*
      - gradle/**
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Functional Tests with Gradle
        run: ./gradlew cucumber --info

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

